### ISSUE TITLE
Unable to add Account Connections

### ISSUE THREAD

**Issue by 0x-Stealth** [Vencord/Vesktop#327]
### Enviourment
Windows 11 22H2 
Latest Stable Windows Vesktop Release

### Description
Attempting to add a connection (that uses outside OAuth2) does not work on Vesktop (probably because it opens a popup on Clean Desktop && Web Clients), this causes it to load indefinitely.

### Reproduction Steps
1. Install Vesktop on Windows
2. Attempt to link a Spotify Account (Fresh Discord)

### Active Plugin List
- CrashHandler
- PlatformIndicators
- MessageLogger

Not sure if this is a Vesktop issue or a me issue, but it's happened before so, worth making a issue.

**Comment by Vendicated** [comment]
fixed in https://github.com/Vencord/Vesktop/commit/38f0330eb24c778326ed930c3e2294d011758319

**Comment by jinetty** [comment]
This issue still persist on Linux. I have this issue, whatever I try to connect, not only Spotify. I am running the client on Wayland session in Arch Linux.
