### ISSUE TITLE
[Linux] Ozone platform hint

### ISSUE THREAD

**Issue by NyaomiDEV** [Vencord/Vesktop#342]
**Is your feature request related to a problem? Please describe.**
This solves a problem with consistency on Wayland desktops.

**Describe the solution you'd like**
The `.desktop` file could have `--ozone-platform-hint=auto` appended to it. It would be possible to pass it straight from the app's code via `app.commandLine.appendSwitch('ozone-platform-hint', 'auto')` but I couldn't get it to ever work in my Electron test thingamajigs.

**Describe alternatives you've considered**
XWayland... uhhhhh.... not in my desktop sorry.

**Additional context**
:sparkles: Fractional scaling! :sparkles:

**Comment by ToxicMushroom** [comment]
This break drag and drop completly on my system
arch, sway, nemo file manager

**Comment by Sqaaakoi** [comment]
> This breaks drag and drop completely on my system arch, sway, nemo file manager

iirc nemo runs through XWayland

**Comment by NyaomiDEV** [comment]
> This breaks drag and drop completely on my system arch, sway, nemo file manager

you should see if drag and drop is working correctly between nemo (xwayland) and any other native wayland client. if that's not the case, you'd need to debug that on your own.

here, running KDE on Wayland, drag and drop correctly works.

**Comment by ToxicMushroom** [comment]
> iirc nemo runs through XWayland
Not for me (using nemo `6.0.2-1` from arch extra)

Drag and drop works to other wayland native apps like gnome's ghex

**Comment by NyaomiDEV** [comment]
> Not for me (using nemo `6.0.2-1` from arch extra)
>
> Drag and drop works to other wayland native apps like gnome's ghex

are you totally sure? what does `xlsclients` show you?

**Comment by ToxicMushroom** [comment]
Ye I'm sure xlsclients doesn't list them, xprop doesn't show a cross and app_ids are present in sway.

No I dont use the flatpak because of this drag and drop (dnd) issue since they also start the client with ozone (just checked again to make sure it didnt get fixed in the meantime). 
I run the vesktop aur package under xwayland most of the time since then dnd works 50% of the time.

**Comment by NyaomiDEV** [comment]
> Ye I'm sure xlsclients doesn't list them, xprop doesn't show a cross and app_ids are present in sway.
> 
> No I dont use the flatpak because of this drag and drop (dnd) issue since they also start the client with ozone (just checked again to make sure it didnt get fixed in the meantime). I run the vesktop aur package under xwayland most of the time since then dnd then works 50% of the time.

it seems to me that your sway configuration is to be checked.

**Comment by ToxicMushroom** [comment]
The only thing that affects dnd I think is `focus_follows_mouse`, turning it on breaks dnd 100% on discord/vesktop running in xwayland while not fixing either (nor the flatpak) on ozone.

Maybe unrelated since I don't know how much different their client works but dnd to discord-screenaudio always works (the run wayland native according to xprop, xlsclients ect). 

https://0x0.st/H00j.txt

**Comment by NyaomiDEV** [comment]
If you feel it doesn't work for you in native Wayland you can use XWayland for now - however, even if this feature gets added, you can still remove the argument yourself until you fix whatever is wrong with your setup.

> Maybe unrelated since I don't know how much different their client works but dnd to discord-screenaudio always works (the run wayland native according to xprop, xlsclients ect).

Screenaudio uses webkitgtk, while Vesktop uses Electron (same as Discord.)

> https://0x0.st/H00j.txt

I can't tell you what's wrong with your setup, as I never used sway. Please do your own research about it. I think, however, that this feature request should move on to reach parity with the Flatpak package and also because of other issues that it would solve (for example again, proper fractional scaling support)

**Comment by Vendicated** [comment]
> No I dont use the flatpak because of this drag and drop (dnd) issue since they also start the client with ozone (just checked again to make sure it didnt get fixed in the meantime).

@ToxicMushroom you can just remove the wayland permission from the flatpak and it'll run in xwayland. for example using flatseal

**Comment by ToxicMushroom** [comment]
It seems to be a chromium issue, I'll see if I can fix it but no promises

**Comment by AAGaming00** [comment]
This should be an (on by default IMO) setting, as on some systems it is helpful while on others it causes issues (like on my dual-gpu laptop where running directly under wayland causes it to keep the dedicated GPU awake)

**Comment by ToxicMushroom** [comment]
This is now fine for me since https://github.com/linuxmint/nemo/issues/3354 was resolved :)

**Comment by Schweeeeeeeeeeeeeeee** [comment]
I don't know why, but I can't get vesktop to launch on hyprland and I think this is why would be pretty useful

**Comment by dumbasPL** [comment]
After a recent update (not sure if system or vesktop) the main window became completely transparent, adding `--ozone-platform-hint=auto` fixed it.

Arch Linux, Gnome 45.4 on Wayland, Nvidia 545.29.06, vesktop 1.5.0 from AUR `vesktop-bin`

**Comment by kaitlynkittyy** [comment]
I'm also having the drag and drop issue on the newest flatpak (1.5.2), running KDE wayland. After I drag a file into the app, everything works properly until I send the message, in which the app instantly stops responding to any mouse input, but the keyboard works fine. I assume this is due to it running in xwayland, but I am not sure.

**Comment by mystchonky** [comment]
> I'm also having the drag and drop issue on the newest flatpak (1.5.2), running KDE wayland. After I drag a file into the app, everything works properly until I send the message, in which the app instantly stops responding to any mouse input, but the keyboard works fine. I assume this is due to it running in xwayland, but I am not sure.

I can also replicate this issue. It works well when using the '+' button in the message box but drag and drop breaks the application. Need to restart the app.

**Comment by mystchonky** [comment]
Could it be this issue ? https://bugs.kde.org/show_bug.cgi?id=482142. This was fixed already and going to be released in plasma 6.1

**Comment by ShayBox** [comment]
I also had to spend hours figuring out this is a Vesktop/Electron issue, and found this issue.
This should really be enabled by default, because it doesn't negatively affect anyone still using X11.
There's also `--use-gl=desktop` which opens the window immediately, instead of after around a minute.

**Comment by Vendicated** [comment]
> This should really be enabled by default, because it doesn't negatively affect anyone still using X11

false. there's a reason this is still not enabled by default in chromium. Just because it is stable for you doesn't mean it is stable for everyone. 

in any case, we already enable this by default inside the flatpak

**Comment by mystchonky** [comment]
> Could it be this issue ? https://bugs.kde.org/show_bug.cgi?id=482142. This was fixed already and going to be released in plasma 6.1

I got plasma 6.1 but the issue still persists. I will go talk to plasma kwin devs and see what's going on. Does Vencord handle any special cases for drag and drop that the devs will need to know about to fix this ?

**Comment by AlphaCraft9658** [comment]
Any updates?

**Comment by Vendicated** [comment]
This flag still causes various issues and essentially has no real benefit so no we will not add this any time soon.

**Comment by severtheskyline** [comment]
So, I guess a little bit of an update, chromium upstream now defaults to wayland by default, this had been known that it would happen for a while now:

https://www.phoronix.com/news/Chromium-Ozone-Wayland-2025

And it seems with chromium 140 it already defaults the ozone platform to wayland.
This is chromium just installed from flathub, no configuration from my side:

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/be3f0073-5a92-4f7e-ba7f-35afaee94dc9" />

Realistically, there's nothing to do on vesktop's end, if the electron version that bases itself on chromium 140 doesn't disable the change, when vesktop updates the flag will default to wayland. I guess I'm here to ask, will vesktop follow upstream chromium/electron or will it still default to xwayland unless the user overwrites it?

**Comment by pm0u** [comment]
not quite the same but i also use fractional scaling on wayland and had very fuzzy fonts until I added `--enable-features=UseOzonePlatform --ozone-platform=wayland` to the .desktop. I honestly don't know entirely what that does but it was recommended for VSCode which also uses electron so I gave it a shot here. Seems to have worked great for me so far.

**Comment by severtheskyline** [comment]
> not quite the same but i also use fractional scaling on wayland and had very fuzzy fonts until I added `--enable-features=UseOzonePlatform --ozone-platform=wayland` to the .desktop. 

That just enables native wayland on chromium/electron, and from that you only need `--ozone-platform-hint=auto` (I don't think this works on weston but weston has basically been relegated to being a car infotainment compositor so it doesn't matter.

**Comment by pm0u** [comment]
> > not quite the same but i also use fractional scaling on wayland and had very fuzzy fonts until I added `--enable-features=UseOzonePlatform --ozone-platform=wayland` to the .desktop.
> 
> That just enables native wayland on chromium/electron, and from that you only need `--ozone-platform-hint=auto` (I don't think this works on weston but weston has basically been relegated to being a car infotainment compositor so it doesn't matter.

It does seem like that has the same effect! thanks for pointing that out
