### ISSUE TITLE
Screenshare with audio enabled breaks video quality

### ISSUE THREAD

**Issue by sysrq-reisub** [Vencord/Vesktop#528]
**Describe the bug**

I can stream fine with or w/o Hardware Acceleration enabled until I turn on the audio source for any application, choosing entire audio or specific applications does not matter

**To Reproduce**

1. Start a screenshare
2. Add an audio source before or after starting the screenshare
3. Video quality breaks completely

**Expected behavior**

Video quality remains the same when an audio source is  selected.

**Screenshots**

- Streaming output

Those are the streams output, in both cases the frame rate is terrible, a single frame is refreshed after a couple of seconds
Quality changes depending whether "prefer smoothness or "prefer clarity" is selected

![photo_2024-04-20_19-22-06](https://github.com/Vencord/Vesktop/assets/7904559/ea1228bd-76a6-4c8c-bb7d-00493011578b)
![photo_2024-04-20_19-22-05](https://github.com/Vencord/Vesktop/assets/7904559/0ed7edc2-7da6-462e-afe0-e3b47f2b994f)

- RTC Debug

Screenshare without selecting an audio source
![Schermata del 2024-04-20 19-07-18](https://github.com/Vencord/Vesktop/assets/7904559/3e8b9d39-9157-4e48-9896-b8132476a0a4)
Frame rate is stable, quality is excellent, tried a fast pacing video game, encoding works correctly as nvtop shows.
![Schermata del 2024-04-20 19-07-12](https://github.com/Vencord/Vesktop/assets/7904559/22045b4c-8d77-4f9b-9b4e-f8f0bc7a7a87)

This is after selecting an audio source after the screenshare was started, with "Prefer clarity" choosen
You can see a sudden drop in frame rate 
![Schermata del 2024-04-20 19-11-52](https://github.com/Vencord/Vesktop/assets/7904559/89838b2c-6b2e-4ef5-a924-cdbcd0a2df62)

This is when "Prefer smoothness" is choosen, video resolution drops to 480x270

![Schermata del 2024-04-20 19-13-23](https://github.com/Vencord/Vesktop/assets/7904559/ca658968-6b67-4715-93d0-ea8934f59da9)

This is the audio section. Doesn't change much I think.

![Schermata del 2024-04-20 19-13-28](https://github.com/Vencord/Vesktop/assets/7904559/d24ff26a-083d-4569-a3c7-b3e95fe23de6)

**Desktop (please complete the following information):**
 - OS/Distro: Fedora Linux 39 (Workstation Edition)
 - Desktop Environment (linux only): GNOME
 - Version: GNOME Shell 45.5

My setup also includes

- DX3 USB DAC, my primary audio output
- Blue Snowball USB Microphone
- 170Hz Gigabyte M27Q monitor on DP-1, freesync disabled
- Benq XL2411Z Second monitor on DP-2 (Video input)-> to HDMI Adapter
- GPU: Radeon RX 7800 XT
- CPU: AMD Ryzen 5 5600

Vesktop versions tried:

- Mainline git, up to date from the last 1 hour.
- #489 

**Command line output**
Started with the following parameters, also enabled venmic debug in case you need it:

**VENMIC_ENABLE_LOG=1 pnpm start**

```
> vesktop@1.5.1 start /home/luca/Documenti/GIT/Vesktop
> pnpm build && electron .


> vesktop@1.5.1 build /home/luca/Documenti/GIT/Vesktop
> tsx scripts/build/build.mts

[2024-04-20 19:13:42.432] [MANGOHUD] [error] [overlay_params.cpp:1003] Failed to read presets file: '/home/luca/.config/MangoHud/presets.conf'
[2024-04-20 19:13:42.432] [MANGOHUD] [error] [overlay_params.cpp:840] Unknown option 'io_stats'
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[Vencord] Installed React Developer Tools
(node:79532) ExtensionLoadWarning: Warnings loading extension at /home/luca/.config/vesktop/ExtensionCache/fmkadmapgofadopljbjfkapdkoienihi:
  Manifest version 2 is deprecated, and support will be removed in 2024. See https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline for details.

(Use `electron --trace-warnings ...` to show where the warning was created)
[arRPC > process] detected game! VA-11 HALL-A
[79570:0420/191344.102905:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[79570:0420/191352.149720:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[79570:0420/191354.294553:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```
Output too long. The rest is here:
[cmdline_output.txt](https://github.com/Vencord/Vesktop/files/15049240/cmdline_output.txt)

 

**Additional context**

What I tried excluding was:

- My DNS server
- My internet connection, I tried my mobile LTE hotspot.
- My operating system, I tried a fresh install of Ubuntu and looks like it's still affected, may need further testing though.
- Changing VA-API drivers on my distro
- Excluding my DX3 Pro DAC and switching to integrated audio
- My secondary monitor

Also

- Reinstalled vesktop completely from scratch
- Removed all user data in .config/vesktop 

OBS correctly records with audio when using the VA-API Video encoder, looks like only Vesktop is affected.

vainfo output:
```
Trying display: wayland
libva info: VA-API version 1.20.0
libva info: Trying to open /usr/lib64/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_20
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.20 (libva 2.20.1)
vainfo: Driver version: Mesa Gallium driver 23.3.6 for AMD Radeon RX 7800 XT (radeonsi, navi32, LLVM 17.0.6, DRM 3.57, 6.8.7-250.vanilla.fc39.x86_64)
vainfo: Supported profile and entrypoints
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileAV1Profile0            :	VAEntrypointVLD
      VAProfileAV1Profile0            :	VAEntrypointEncSlice
      VAProfileNone                   :	VAEntrypointVideoProc
```

However, it looks like even after disabling "hardware acceleration" on the settings and turning off the encoding support cmdline flags in index.ts the issue is still present. 

May not be related to VA-API video encoding.

I haven't found any issue similar to mine

Sorry for the TL;DR

**Comment by PolisanTheEasyNick** [comment]
FPS and resolution drops because of insane low bitrate when selected audio source.
I will retest it on my machine in around 3-4 hours.

**Comment by sysrq-reisub** [comment]
This is a footage of the actual screenshare output from another computer. 

https://github.com/Vencord/Vesktop/assets/7904559/93c8bc18-8370-475c-b1f8-3abe0d90fe9a

Audio was enabled later on. Absolutely perfect before as you can see. Encoding was working fine for 30% of usage, after the audio was enabled, dropped to 0%

**Comment by Curve** [comment]
Could happen because the screen share picker for audio adds an audio track - maybe the video properties are reset here somehow?

**Comment by PolisanTheEasyNick** [comment]
About stream preview error I think it's okay because I received it even when my bitrate was ok.
About adding audio track to stream it may cause bitrate drops, but we need to retest it. I will try to reproduce issue and investigate it further.

**Comment by Nazo96** [comment]
Hi,
I also have this issue and I'd like to add one thing.
When streaming and NO ONE is watching my stream, the bitrate target is 8000 kpbs and the actual bitrate hovers around 7k and 8k (1080p 60fps prefer clarity)

As soon as someone joins the stream, the bitrate goes to 28kpbs.

This issue is not present when streaming without and audio source.

**Comment by Curve** [comment]
> About stream preview error I think it's okay because I received it even when my bitrate was ok. About adding audio track to stream it may cause bitrate drops, but we need to retest it. I will try to reproduce issue and investigate it further. 30 kbit looks like normal bitrate for audio, maybe bitrate for added audio track accidentally set to video too?

That's what I thought as well ^^

**Comment by Curve** [comment]
> Hi, I also have this issue and I'd like to add one thing. When streaming and NO ONE is watching my stream, the bitrate target is 8000 kpbs and the actual bitrate hovers around 7k and 8k (1080p 60fps prefer clarity and with an audio souce)
> 
> As soon as someone joins the stream, the bitrate goes to 28kpbs.
> 
> This issue is not present when streaming without an audio source.

@PolisanTheEasyNick Maybe that's caused by the same discord call that messes with the video source shortly after it's started (for which you added the setTimeout call)

**Comment by EtereosDawn** [comment]
fedora 40 gnome 46 latest update

I'm using the PR where the bitrate fix was added to the main branch, I can confirm it has the same issue. I haven't run a git pull until now. I'm using the same versions of the latest merge fix for the main branch so far. however, crashes and delays are fixed when launching from the terminal. any changes to the main branch do not come from any changes to the source code. Maybe it's something related to the discord side. When using the flags the problem is fixed on my side:

 `vesktop --enable-features=VaapiVideoDecoder,VaapiVideoEncoder`

**Comment by EtereosDawn** [comment]
this is the pr I'm using, https://github.com/Vencord/Vesktop/pull/489 the most recent ones suffer from the same problem. some also do not play sound in the case of the "main branch" currently.

something interesting to say is that when using the official web discord my friends got lags. "https://discord.com/channels/@me" something I've never seen when using discord web through Google Chrome.

**Comment by sysrq-reisub** [comment]
btw, I did some further testing, looks that anything before #489 works fine for me...

right now I'm on #499 and tested a bunch of commits, then did a git bisect (I'm no good at this, I don't know if I am doing this right)

```
> 8eaa5206b98ce7029b6879cc2ce361c2ae5f6239 is the first bad commit
commit 8eaa5206b98ce7029b6879cc2ce361c2ae5f6239
Author: kaitlynkitty <87152313+kaitlynkittyy@users.noreply.github.com>
Date:   Wed Apr 17 19:40:03 2024 -0400

    overhaul & improve Linux screenshare (#489)
    
    Fixes fps/resolution not properly being applied
    Enables hardware encoding via vaapi
    Redesigns stream picker modal
    
    Co-authored-by: kaitlynkittyy <kaitlynyaadev@kaitlynyaa.dev>
    Co-authored-by: Oleh Polisan <polisanoleg@gmail.com>
    Co-authored-by: Vendicated <vendicated@riseup.net>

 src/main/index.ts                             |   8 +-
 src/renderer/components/ScreenSharePicker.tsx | 139 +++++++++++++++++++++-----
 src/renderer/components/screenSharePicker.css |  16 +++
 src/renderer/patches/index.ts                 |   2 +-
 src/renderer/patches/screenShareAudio.ts      |  42 --------
 src/renderer/patches/screenShareFixes.ts      |  69 +++++++++++++
 6 files changed, 208 insertions(+), 68 deletions(-)
 delete mode 100644 src/renderer/patches/screenShareAudio.ts
 create mode 100644 src/renderer/patches/screenShareFixes.ts
```

**Comment by sysrq-reisub** [comment]
In case you want to hear a funny story to tell your friends or family, here is one

So for some reason today I was not able to reproduce the issue anymore
Also, the latest commits broke audio sources at all (I swear it worked yesterday????) so I'm currently on #489 where it works

And... I couldn't reproduce it anymore... I was starting to think my account was limited yesterday somehow, BUT then the only thing that changed from yesterday was the discord client where I was testing the stream output with my discord alt account...

It turns out when I use my other computer I just fixed today which has Vesktop, the stream mostly looks fine, then if I try again using an android device the stream messes up the same way as yesterday, it also messes up with a web client... AND with ANOTHER computer using a regular discord client on Ubuntu.

So to be sure I'm not crazy, I had an old windows install, I started a screenshare from a regular discord install, then joined again with my other account on the phone I was testing the stream with, and it was working fine from all those devices.

Then again, I switched to the official discord client on my laptop which was showing the stream just fine with Vesktop, then the issue came back again.
 
So long story short, it all depends from the client you are using to watch the stream, **AND** if you have selected an audio source... 

I also tried an old version of Vesktop and fired up a stream the same way, so it always happened for me.

What changes when looking at the RTC debug, is the following:

- Bitrate target remains high when Vesktop client is used on a desktop

![Schermata del 2024-04-21 13-12-30](https://github.com/Vencord/Vesktop/assets/7904559/3ec01a21-247c-4b1b-9b51-34eb1a2d4987)

- Bitrate target drops insanely when the stream is watched from a Android phone
![Schermata del 2024-04-21 13-13-08](https://github.com/Vencord/Vesktop/assets/7904559/cc63063b-3029-42a8-b29c-7650dfa0374e)


Also I noticed that the bitrate section disappears and reappears after a couple of seconds, meaning it may be resetting itself somehow?

**Comment by sysrq-reisub** [comment]
![immagine](https://github.com/Vencord/Vesktop/assets/7904559/459b5b47-f3ad-4f43-ab44-3b9657506163)

Red stripe is when my android phone joined the stream. Dropped the bitrate to ~30Kbps

I'm re-testing with a couple of friends, totally client dependent, I had my friend join with a Windows discord client and he was watching the stream correctly, then another friend with an android phone joined, the stream was still fluent.

Re-made the stream with the same friend with the android client and the bitrate was back to 30 Kbps~ and quality totally crap.

**Comment by Nazo96** [comment]
@sysrq-reisub Can confirm.
With my alt account the stream works with audio, no bitrate drops.

**Comment by kaitlynkittyy** [comment]
> @sysrq-reisub Can confirm. With my alt account the stream works with audio, no bitrate drops.
> 
> EDIT: I tried streaming from my alt account (Vesktop) to my main account (Official Discord) and the bitrate drops again.

i believe the bitrate drop only occurs when someone starts watching

**Comment by PolisanTheEasyNick** [comment]
Retested with friend on Windows and when he started watching stream bitrate dropped to 30, so most probably it's not depending on client.
Still looks like somewhere bitrate takes from audio track content instead of video :c

**Comment by sysrq-reisub** [comment]
> > @sysrq-reisub Can confirm. With my alt account the stream works with audio, no bitrate drops.
> > EDIT: I tried streaming from my alt account (Vesktop) to my main account (Official Discord) and the bitrate drops again.
> 
> i believe the bitrate drop only occurs when someone starts watching

It does but from what I have experienced happens only when a client has a specific decoder.

> Retested with friend on Windows and when he started watching stream bitrate dropped to 30, so most probably it's not depending on client. Still looks like somewhere bitrate takes from audio track content instead of video :c

So far 100% of the times the stream fixes itself whenever I join with the Vesktop client on my laptop with my alt account or with a Windows client with hardware acceleration enabled (but in this case depends from the video card decoder I suppose) 

Tried with Windows myself, also found another Discord bug whether the Hardware Acceleration its not enabled anymore after toggling it off an on, and requires local user data to be deleted... But in any case the windows client acts differently every time, I couldn't 100% reproduce it, sometimes the decoder is ffmpeg, other times "electron" as seen from the debug page and hardware usage

However, one thing I am certain of is Vesktop uses 100% of the times WebRTC as video decoder, and the stream is always perfect in that case, and fixes it for everyone else

**Comment by tcharchar** [comment]
Attempt using `--enable-features=WebRTCPipeWireCapturer`, perhaps. Using 720p60 and sometimes 1080p60 according to my friends runs perfectly well. My full vesktop launch command is the following:
```
vesktop --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform-hint=auto --enable-features=VaapiVideoDecoder,VaapiVideoEncoder,WebRTCPipeWireCapturer
```

**Comment by Nazo96** [comment]
> NOTE 2: I'm using the latest vesktop version, built literally ~45 minutes ago with pnpm package --linux pacman

I built the latest vesktop version and now there is no audio channel, even if I choose it in the audio source list.
The bitrate is fine, but no audio :(

**Comment by Vendicated** [comment]
try building https://github.com/Vencord/Vesktop/pull/531 instead

**Comment by Nazo96** [comment]
> try building #531 instead

Thank you!
The audio channel is back, but the main issue persists. Bitrate drops to 30kbps as soon as someone watches the stream.
I tried @tcharchar launch commands with no luck.

**Comment by kaitlynkittyy** [comment]
i have been able to confirm that the bitrate is lowered to 29.17kbps on my machine when streaming with audio AND someone is watching, but as soon as someone else starts watching (total of 2 viewers) the bitrate gets raised to around 1400kbps. This issue is even more strange than before, and I am entirely at a loss as to how we should go about fixing this. Here's to hoping someone has an idea lol.

**Comment by kaitlynkittyy** [comment]
> i have been able to confirm that the bitrate is lowered to 29.17kbps on my machine when streaming with audio AND someone is watching, but as soon as someone else starts watching (total of 2 viewers) the bitrate gets raised to around 1400kbps. This issue is even more strange than before, and I am entirely at a loss as to how we should go about fixing this. Here's to hoping someone has an idea lol.

Also, I cannot confirm that this is the case, as it was very sporadic as to whether or not it happened, but it seemed to not be an issue when I had someone watching from a web client. This needs more testing to be solidified as a cause though, but if it is, it may be an issue/change to discord's server systems.

**Comment by sysrq-reisub** [comment]
So I upgraded to the latest git build.
In any case what it came to my understanding is it totally depends

**Comment by tcharchar** [comment]
> > NOTE 2: I'm using the latest vesktop version, built literally ~45 minutes ago with pnpm package --linux pacman
> 
> I built the latest vesktop version and now there is no audio channel, even if I choose it in the audio source list. The bitrate is fine, but no audio :(

Oh yeah you're right. Audio indeed does not work. My apologies.

**Comment by sysrq-reisub** [comment]
So I upgraded to the latest git build, audio now works fine
In any case what it came to my understanding is it totally depends from the client video decoder, somehow they influence the stream bitrate for everyone 

"Bad" clients:
- Windows ones work  _sometimes_ as long they are using hardware decoders
- Some android clients, my Pixel 8 for example and a couple of other phones break the stream
- Some web clients in my case I was using Firefox
- Regular Discord clients on Linux distros (they probably have basic software decoding) 

"Good" clients:
- Vesktop which uses WebRTC is fine in both windows and linux
- Some Windows discord clients

Also, apparently you just need one of the "good" clients to fix the stream for everyone. I made my alt join my streams so everyone can look at them without it being a slideshow

This is what you see when using Vesktop as a client, then rejoining the stream with a regular discord client on a Linux dsitro, and joining again with Vesktop fixing the stream again.

https://github.com/Vencord/Vesktop/assets/7904559/6e51bf29-4636-49f7-b5fa-77d5d70d9b9d

This is what was happening on my computer where the screenshare started while I was recording the previous video, you can see the drop to 30Kbps then it up again.

https://github.com/Vencord/Vesktop/assets/7904559/6b2c045b-5e26-4f73-811b-7c05c2802253

**Comment by Curve** [comment]
> > > NOTE 2: I'm using the latest vesktop version, built literally ~45 minutes ago with pnpm package --linux pacman
> > 
> > 
> > I built the latest vesktop version and now there is no audio channel, even if I choose it in the audio source list. The bitrate is fine, but no audio :(
> 
> Oh yeah you're right. Audio indeed does not work. My apologies.

With the latest commit audio should work

**Comment by Curve** [comment]
> So I upgraded to the latest git repo, audio now works fine In any case what it came to my understanding is it totally depends from the client video decoder, somehow they influence the stream bitrate for everyone
> ~snip~

I am lost for words lmao

**Comment by tcharchar** [comment]
> > So I upgraded to the latest git repo, audio now works fine In any case what it came to my understanding is it totally depends from the client video decoder, somehow they influence the stream bitrate for everyone
> > ~snip
> 
> I am lost for words lmao

This might be more of an issue on Discord's side than Vesktop or really anyone; besides the audio issues I suppose. There's literally an ongoing bug in Discord Canary which makes voice chats absolutely unusable as it plays back garbage, unintelligible data.

**Comment by Cynosphere** [comment]
> There's literally an ongoing bug in Discord Canary which makes voice chats absolutely unusable as it plays back garbage, unintelligible data.

It was caused by a broken build of discord_voice and was fixed in ~24 hours. Anyone who still has the issue has not updated since.

**Comment by PolisanTheEasyNick** [comment]
I have some new info about it.
If we create a stream with sound, then we will get 30kbit issue, but if we at same time start camera stream, then we will get for camera our needed bitrate and settings:
![image](https://github.com/Vencord/Vesktop/assets/39007846/2a453c41-85f6-4f2c-8a31-30f41a0cb880)
Looks like we need to more deeply investigate it and add some new workarounds.

**Comment by PolisanTheEasyNick** [comment]
I'm able to reproduce this bug on Windows Google Chrome browser at native discord web version. As long as this is a discord bug, I really have doubts that there is a way to fix it :c

**Comment by Fleeym** [comment]
Hey there, here to give my little research into this bug.

I've tested 4 cases:

1. Streaming alone
2. Streaming with a Vesktop client
3. Streaming with a "bad" client
4. Streaming with a Vesktop + "bad" clients

1 and 2 gave 5000kbps bitrate. 3 gave 30kbps. Most interestingly, streaming for a Vesktop + "bad" client set my bitrate to 1400kbps, as if it's trying to "balance out" between the 2 of them. Maybe it thinks the "bad" client can't process the stream it's sending or something?

**Comment by kaitlynkittyy** [comment]
> Hey there, here to give my little research into this bug.
> 
> I've tested 4 cases:
> 
>     1. Streaming alone
> 
>     2. Streaming with a Vesktop client
> 
>     3. Streaming with a "bad" client
> 
>     4. Streaming with a Vesktop + "bad" clients
> 
> 
> 1 and 2 gave 5000kbps bitrate. 3 gave 30kbps. Most interestingly, streaming for a Vesktop + "bad" client set my bitrate to 1400kbps, as if it's trying to "balance out" between the 2 of them. Maybe it thinks the "bad" client can't process the stream it's sending or something?

I believe the 1400kbps thing happens once 2 people start watching. I cannot be sure though, not much has been fully researched.

**Comment by Fleeym** [comment]
> > Hey there, here to give my little research into this bug.
> > I've tested 4 cases:
> > ```
> > 1. Streaming alone
> > 
> > 2. Streaming with a Vesktop client
> > 
> > 3. Streaming with a "bad" client
> > 
> > 4. Streaming with a Vesktop + "bad" clients
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 1 and 2 gave 5000kbps bitrate. 3 gave 30kbps. Most interestingly, streaming for a Vesktop + "bad" client set my bitrate to 1400kbps, as if it's trying to "balance out" between the 2 of them. Maybe it thinks the "bad" client can't process the stream it's sending or something?
> 
> I believe the 1400kbps thing happens once 2 people start watching. I cannot be sure though, not much has been fully researched.

Yeah, I got that with 2 people watching, a Vendesk and a browser (firefox)

**Comment by kaitlynkittyy** [comment]
I tested this in a windows vm with stock discord web in chrome, and the issue persists when streaming to stock discord desktop clients (also on windows) so we can pretty confidently say that this is discord's issue to fix on their end

**Comment by Fleeym** [comment]
Oh boy... that surely won't take ages

**Comment by Reonu** [comment]
So the issue affects people streaming from Windows to Windows? Then there's actually a good chance they'll fix it quickly

**Comment by PeaceNira** [comment]
has anyone found a solution to this?

**Comment by Nazo96** [comment]
> I tested this in a windows vm with stock discord web in chrome, and the issue persists when streaming to stock discord desktop clients (also on windows) so we can pretty confidently say that this is discord's issue to fix on their end

This issue was not present before #489 though.
I used to stream low intensity games and youtube videos with audio without bitrate drops to any Discord user (web clients and official clients) The resolution would never decrease (720p 30fps) and the quality was good most of the times.
The only issue was huge frame drops when streaming fast paced games where the camera makes sudden movements (FPSes, MOBAs, fast platformers).

Now the issue is completely different.
Choosing to stream with audio completely breaks the stream, where before it did not make a difference.
To be honest this is a downgrade for those who want to stream to non-Vesktop users.
But if you're planning to stream without audio or to Vesktop users, it's a huge upgrade instead.

**Comment by PolisanTheEasyNick** [comment]
> This issue was not present before #489 though.
This bug is not regression after #489 because Discord do something on their side right after we fixed almost all of screensharing. You can try to install Vesktop at df05d12 commit before #489 merge, and you will get the same bitrate drop. Also, as mentioned upper, this bug is reproducible even in native discord web version without Vencord and/or Vesktop.

**Comment by Nazo96** [comment]
> This bug is not regression after #489 because Discord do something on their side right after we fixed almost all of screensharing. 

Oh shoot, you're right.
What a bummer, if Discord did not push that update on their side we would have perfect streaming now.
I have no words :(

**Comment by PolisanTheEasyNick** [comment]
> > This bug is not regression after #489 because Discord do something on their side right after we fixed almost all of screensharing. 
> 
> Oh shoot, you're right.
> What a bummer, if Discord did not push that update on their side we would have perfect streaming now.
> I have no words :(

We actually had perfect streaming while developing for about 2-3 days :D

**Comment by Nazo96** [comment]
> We actually had perfect streaming while developing for about 2-3 days :D

YES! Then I'm not crazy!!!!
The very first day everything was working!
You people did an amazing job anyway!
Hoping that discord reverts whatever they've done.

**Comment by GijsvandenHoven** [comment]
> So the issue affects people streaming from Windows to Windows? Then there's actually a good chance they'll fix it quickly

Specifically for Web Clients, but it looks like it. 
I found this page after having the same issue with bitrate and audio, on Linux Mint with X11.

I was trying to stream to 3 unmodified, desktop Windows discord clients, at least one of which is using hardware acceleration.
Thus making that a 'good client' ? (hardware acceleration setting = using hardware decoder like some in the issue mention helps it?)

One of the windows users tried to stream the same thing instead, absolutely zero issues for anyone.

I know this isn't a very detailed report, I haven't really chased down the others for their discord settings that much.

Either way, this last week there's been plenty of streaming in my group, and I'm the only one having issues. I am also the only one using Linux & Vesktop.


__________

I'm a little more pessimistic about Discord fixing it quickly, personally. How big is the user-base of 'web client users that are trying to stream' ? I vaguely estimate it's less or equal in size of 'Linux users trying to stream'. 

That user-base has not been able to stream properly for _years_, Discord doesn't seem to care. The only way to stream with audio on Linux is through the awesome community effort of Vencord and other 3rd party clients.

**Comment by ArbitraryRenaissance** [comment]
> I tested this in a windows vm with stock discord web in chrome, and the issue persists when streaming to stock discord desktop clients (also on windows) so we can pretty confidently say that this is discord's issue to fix on their end

Have you submitted a bug report to Discord?  I haven't found anyone talking about this issue outside of this thread.

**Comment by PolisanTheEasyNick** [comment]
> Have you submitted a bug report to Discord? I haven't found anyone talking about this issue outside of this thread.
I submitted, but I do not believe that they will do anything about it.

**Comment by kaitlynkittyy** [comment]
> > Have you submitted a bug report to Discord? I haven't found anyone talking about this issue outside of this thread.
> 
> I submitted, but I do not believe that they will do anything about it.

I hope they do, as this is quite a large problem for all web users

**Comment by Sphirye** [comment]
I though my laptop performance magically just died until i found this, glad to know im not crazy! Im totally experiencing the same main deal, screensharing was perfectly working until i switched from fedora 37 to 40 and gnome 6, because of this i was already blaming the entire os 

Having discord releasing update almost after fedora 40 came out really blured up everything

**Comment by PolisanTheEasyNick** [comment]
Okay, here are some updates.
Yesterday (30.04) Discord updated web version from 287337 to 289103. Kaitlyn noticed that streaming from Vesktop to Browser (and some clients) was fixed (if we can say so). At that time I was able to stream from Vesktop to another account on Chromium without bitrate loses, however while streaming from Vesktop to Firefox I could see drops to 29.17 kbit/s.
Today(? 01.05) Discord updated web version to 289379 and rn I'm able to stream from Vesktop to friend on Windows, which uses native Discord client. 
So it means that Discord team actually doing some job with all this stuff.
What also interesting, sometimes I had 29.17 kbit/s issue when stream is created with sound but no sound actually transmitted, but when I enable video, for example, which starts transmitting sound, I receive bitrate raising:
![image](https://github.com/Vencord/Vesktop/assets/39007846/c43d6d50-8e9e-4c8b-852e-75629b73de52)
Summarizing, I think we need more tests. For not spamming at this thread, if you did some tests then please react at this post with :+1: if you CANNOT reproduce this issue and with :-1: if you still have 29.17 kbit/s issue.
Anyway, we need to wait more time for Discord team to fix it completely, because it may still be buggy.

**Comment by kaitlynkittyy** [comment]
> Okay, here are some updates. Yesterday (30.04) Discord updated web version from 287337 to 289103. Kaitlyn noticed that streaming from Vesktop to Browser (and some clients) was fixed (if we can say so). At that time I was able to stream from Vesktop to another account on Chromium without bitrate loses, however while streaming from Vesktop to Firefox I could see drops to 29.17 kbit/s. Today(? 01.05) Discord updated web version to 289379 and rn I'm able to stream from Vesktop to friend on Windows, which uses native Discord client. So it means that Discord team actually doing some job with all this stuff. What also interesting, sometimes I had 29.17 kbit/s issue when stream is created with sound but no sound actually transmitted, but when I enable video, for example, which starts transmitting sound, I receive bitrate raising: ![image](https://private-user-images.githubusercontent.com/39007846/327247133-c43d6d50-8e9e-4c8b-852e-75629b73de52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NDU5MjgsIm5iZiI6MTcxNDc0NTYyOCwicGF0aCI6Ii8zOTAwNzg0Ni8zMjcyNDcxMzMtYzQzZDZkNTAtOGU5ZS00YzhiLTg1MmUtNzU2MjliNzNkZTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDE0MTM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMGE2MTZmZmUzZmZkZGFiYzM4ZGM1YTllZDc4NWQ3OWE2YjM5ODZhNTFiNTcxOGE4ZTUxMGE3Yzk3NTBmYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i6Bdnl-WG1yljs04LySkb_wN0n4iUHF-zZ3HKXYWxnY) Summarizing, I think we need more tests. For not spamming at this thread, if you did some tests then please react at this post with 👍 if you CANNOT reproduce this issue and with 👎 if you still have 29.17 kbit/s issue. Anyway, we need to wait more time for Discord team to fix it completely, because it may still be buggy.

It looks to me like the consensus is that this is entirely fixed. I think this is ready to close :3

**Comment by sysrq-reisub** [comment]
Lookslike it was fixed between Vesktop and some Android clients, a week ago, but now I'm reproducing the issue again, same with Vesktop and Firefox, Vesktop and Windows works fine though. 
Am I the only one?

**Comment by clanps** [comment]
I'm also having this issue, turning off audio on the stream makes the bit rate go back up.

**Comment by PrimalPimmy** [comment]
This is still a problem. Using Fedora KDE with latest version of Vesktop

**Comment by ff7freddy** [comment]
I'm also experiencing this problem in Bazzite Fedora KDE. Updating Vesktop to the latest did not fix for me. Viewers of my streams say the picture looks much better when audio is disabled.

**Comment by Cherryda** [comment]
> I'm also experiencing this problem in Bazzite Fedora KDE, using Vesktop. Updating Vesktop to the latest did not fix for me. Viewers of my streams say the picture looks much better when audio is disabled.

Same issue in my setup, looks like Discord upstream broke screensharing again.

**Comment by Nazo96** [comment]
Yes, the issue came back, but it does not to seem as problematic as before.
I can stream normally with audio to some people, but not to others.
Depends on the "viewer"'s client.

**Comment by AlephNought0** [comment]
So I found a workaround for this problem.

When you start a stream with audio on vesktop a new audio node is created called ``vencord-screen-share`` which connects to ``Chromium input-1`` (which was also created). After cutting the connection between ``vencord-screenshare`` and ``Chromium-input 1`` (using qpwgraph for example), making the stream have no audio basically, the stream started to have proper quality. When I connected ``vencord-screen-share`` to the original ``Chromium-input`` (so basically your microphone) people could hear the audio nicely and see the video without lags and without the bad quality. This only works when starting the stream with audio chosen and then reconnecting it. The audio sounds bad when ``vencord-screen-share`` isn't connected to some node basically. Do note that you won't be heard properly when audio is playing because it is going over you.

Stream with ``Chromium-input 1``
![image](https://github.com/user-attachments/assets/0a0e87ca-0b11-40d9-b52e-51981c7f66f6)
![image](https://github.com/user-attachments/assets/bb7b188d-25df-4b02-8a4a-ac85d5a5d409)

Stream with ``Chromium-input``
![image](https://github.com/user-attachments/assets/b7d87a95-f9be-4423-a5d3-d8669098ecc5)
![image](https://github.com/user-attachments/assets/aafb1da1-958a-4762-88cb-a58d257bb7b3)

**Comment by Curve** [comment]
While this is a little dumb we could also automate this (wait until Bitrate Hits a specific threshold and only then start Venmic)

**Comment by pavelgrigoriev** [comment]
> So I found a workaround for this problem.
> 
> When you start a stream with audio on vesktop a new audio node is created called `vencord-screen-share` which connects to `Chromium input-1` (which was also created). After cutting the connection between `vencord-screenshare` and `Chromium-input 1` (using qpwgraph for example), making the stream have no audio basically, the stream started to have proper quality. When I connected `vencord-screen-share` to the original `Chromium-input` (so basically your microphone) people could hear the audio nicely and see the video without lags and without the bad quality. This only works when starting the stream with audio chosen and then reconnecting it. The audio sounds bad when `vencord-screen-share` isn't connected to some node basically. Do note that you won't be heard properly when audio is playing because it is going over you.
> 
> Stream with `Chromium-input 1` ![image](https://private-user-images.githubusercontent.com/64273472/349307651-0a0e87ca-0b11-40d9-b52e-51981c7f66f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1OTY5NjcsIm5iZiI6MTcyMTU5NjY2NywicGF0aCI6Ii82NDI3MzQ3Mi8zNDkzMDc2NTEtMGEwZTg3Y2EtMGIxMS00MGQ5LWI1MmUtNTE5ODFjN2Y2NmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDIxMTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MDI5MjdmODJmMjg2ODQ4YTJkODJiYThmMTgzZWViYTc3OWY4Nzc4NDc2MGE3N2YwZjhmZjdhOTU2NTI0NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ynEV1bav-q-_db3ggbD0VUu5Ike2jEIE8TS7MZufXas) ![image](https://private-user-images.githubusercontent.com/64273472/349307712-bb7b188d-25df-4b02-8a4a-ac85d5a5d409.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1OTY5NjcsIm5iZiI6MTcyMTU5NjY2NywicGF0aCI6Ii82NDI3MzQ3Mi8zNDkzMDc3MTItYmI3YjE4OGQtMjVkZi00YjAyLThhNGEtYWM4NWQ1YTVkNDA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDIxMTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MzY3MGE4NjU1OTM2YmM0MDM3MmYyOTE1NDk5MGZkZmQ3YzhiNTBkNzkxMjQxODc4NWFiMTYxYzg0YTIwOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7FOrEbiurKGn59iH1anFyADFQXXj7BDkN5xnsq8J45w)
> 
> Stream with `Chromium-input` ![image](https://private-user-images.githubusercontent.com/64273472/349307935-b7d87a95-f9be-4423-a5d3-d8669098ecc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1OTY5NjcsIm5iZiI6MTcyMTU5NjY2NywicGF0aCI6Ii82NDI3MzQ3Mi8zNDkzMDc5MzUtYjdkODdhOTUtZjliZS00NDIzLWE1ZDMtZDg2NjkwOThlY2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDIxMTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NjE4N2NhYTI0NGU3NGJlZDA4OTZkMzk4MmNmMzhlODk5OWEzZTQ5NzM4NmQxNmQ2ZWU1NDdjN2QyZmY3YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lj0MaMFPCSb3BA2JRo-JOqrGF9Ae3wQgjyygVPfzNkg) ![image](https://private-user-images.githubusercontent.com/64273472/349307993-aafb1da1-958a-4762-88cb-a58d257bb7b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1OTY5NjcsIm5iZiI6MTcyMTU5NjY2NywicGF0aCI6Ii82NDI3MzQ3Mi8zNDkzMDc5OTMtYWFmYjFkYTEtOTU4YS00NzYyLTg4Y2ItYTU4ZDI1N2JiN2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDIxMTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MWQ4ZDNmYzM5MmU0YjZhMTZhYmU1OGUxOTlkMWI3ZWQwZDkyMmEwMTcyNmY5ZjUzYTYyYWVkZWE5ODY2MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DQ3NBPBlzKJX7Jz7rVYcWwzNZT9OWl5VHQPn3zs_zXE)

I have the same problem, and your solution helped me, maybe, to reopen the problem?

**Comment by AlephNought0** [comment]
> > So I found a workaround for this problem.
> > 
> > When you start a stream with audio on vesktop a new audio node is created called `vencord-screen-share` which connects to `Chromium input-1` (which was also created). After cutting the connection between `vencord-screenshare` and `Chromium-input 1` (using qpwgraph for example), making the stream have no audio basically, the stream started to have proper quality. When I connected `vencord-screen-share` to the original `Chromium-input` (so basically your microphone) people could hear the audio nicely and see the video without lags and without the bad quality. This only works when starting the stream with audio chosen and then reconnecting it. The audio sounds bad when `vencord-screen-share` isn't connected to some node basically. Do note that you won't be heard properly when audio is playing because it is going over you.
> > 
> > Stream with `Chromium-input 1` ![image](https://private-user-images.githubusercontent.com/64273472/349307651-0a0e87ca-0b11-40d9-b52e-51981c7f66f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1OTY5NjcsIm5iZiI6MTcyMTU5NjY2NywicGF0aCI6Ii82NDI3MzQ3Mi8zNDkzMDc2NTEtMGEwZTg3Y2EtMGIxMS00MGQ5LWI1MmUtNTE5ODFjN2Y2NmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDIxMTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MDI5MjdmODJmMjg2ODQ4YTJkODJiYThmMTgzZWViYTc3OWY4Nzc4NDc2MGE3N2YwZjhmZjdhOTU2NTI0NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ynEV1bav-q-_db3ggbD0VUu5Ike2jEIE8TS7MZufXas) ![image](https://private-user-images.githubusercontent.com/64273472/349307712-bb7b188d-25df-4b02-8a4a-ac85d5a5d409.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1OTY5NjcsIm5iZiI6MTcyMTU5NjY2NywicGF0aCI6Ii82NDI3MzQ3Mi8zNDkzMDc3MTItYmI3YjE4OGQtMjVkZi00YjAyLThhNGEtYWM4NWQ1YTVkNDA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDIxMTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MzY3MGE4NjU1OTM2YmM0MDM3MmYyOTE1NDk5MGZkZmQ3YzhiNTBkNzkxMjQxODc4NWFiMTYxYzg0YTIwOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7FOrEbiurKGn59iH1anFyADFQXXj7BDkN5xnsq8J45w)
> > 
> > Stream with `Chromium-input` ![image](https://private-user-images.githubusercontent.com/64273472/349307935-b7d87a95-f9be-4423-a5d3-d8669098ecc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1OTY5NjcsIm5iZiI6MTcyMTU5NjY2NywicGF0aCI6Ii82NDI3MzQ3Mi8zNDkzMDc5MzUtYjdkODdhOTUtZjliZS00NDIzLWE1ZDMtZDg2NjkwOThlY2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDIxMTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NjE4N2NhYTI0NGU3NGJlZDA4OTZkMzk4MmNmMzhlODk5OWEzZTQ5NzM4NmQxNmQ2ZWU1NDdjN2QyZmY3YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lj0MaMFPCSb3BA2JRo-JOqrGF9Ae3wQgjyygVPfzNkg) ![image](https://private-user-images.githubusercontent.com/64273472/349307993-aafb1da1-958a-4762-88cb-a58d257bb7b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1OTY5NjcsIm5iZiI6MTcyMTU5NjY2NywicGF0aCI6Ii82NDI3MzQ3Mi8zNDkzMDc5OTMtYWFmYjFkYTEtOTU4YS00NzYyLTg4Y2ItYTU4ZDI1N2JiN2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDIxMTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MWQ4ZDNmYzM5MmU0YjZhMTZhYmU1OGUxOTlkMWI3ZWQwZDkyMmEwMTcyNmY5ZjUzYTYyYWVkZWE5ODY2MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DQ3NBPBlzKJX7Jz7rVYcWwzNZT9OWl5VHQPn3zs_zXE)
> 
> I have the same problem, and your solution helped me, maybe, to reopen the issue?

I do believe that the issue should be reopened. It is still clear that people still suffer from this, including me.

**Comment by willowispll** [comment]
> a little dumb we could also automate this (wait until Bitrate Hits a specific threshold and only then start Venmic)

have you managed to automate it?

**Comment by AlephNought0** [comment]
Not sure if this is exactly what caused the issue but sometime later I have switched from hyprland (and xdph) to niri and ever since streaming with audio worked flawlessly.

**Comment by willowispll** [comment]
> Not sure if this is exactly what caused the issue but sometime later I have switched from hyprland (and xdph) to niri and ever since streaming with audio worked flawlessly.

also using niri rn, still have this issue

**Comment by biscober** [comment]
I am also suffering from this issue.  Is there a workable solution to this?  It's not clear to me from reading the past comments.

**Comment by willowispll** [comment]
> I am also suffering from this issue. Is there a workable solution to this? It's not clear to me from reading the past comments.

@biscober this works:

> So I found a workaround for this problem.
> 
> When you start a stream with audio on vesktop a new audio node is created called `vencord-screen-share` which connects to `Chromium input-1` (which was also created). After cutting the connection between `vencord-screenshare` and `Chromium-input 1` (using qpwgraph for example), making the stream have no audio basically, the stream started to have proper quality. When I connected `vencord-screen-share` to the original `Chromium-input` (so basically your microphone) people could hear the audio nicely and see the video without lags and without the bad quality. This only works when starting the stream with audio chosen and then reconnecting it. The audio sounds bad when `vencord-screen-share` isn't connected to some node basically. Do note that you won't be heard properly when audio is playing because it is going over you.

**Comment by corigne** [comment]
Has anyone communicated this bug upstream?

If so, could you please post the corresponding upstream bug-ticket or nearest equivalent communication?

If not, would it be a huge ask for someone with the technical expertise and understanding of the problem to do so?

Going the last few meters in good faith to close the loop would be a lot better than just letting a known issue sit. That being said, I will happily submit tickets where needed, but it may be better for someone who worked the issue and understands it to do so.

**Comment by Yot360** [comment]
This issue shouldn't even be marked as closed

**Comment by sysrq-reisub** [comment]
As for today, official Discord Canary (or at least the electron version they are using) enabled hardware encoding via vaapi at least for my amd RX 7800 XT and vaapi setup natively

(Shows as h264 in debug page)

vainfo
```
Trying display: wayland
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib64/dri-nonfree/radeonsi_drv_video.so
libva info: Trying to open /usr/lib64/dri-freeworld/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.22 (libva 2.22.0)
vainfo: Driver version: Mesa Gallium driver 25.3.6 for AMD Radeon RX 7800 XT (radeonsi, navi32, LLVM 21.1.8, DRM 3.64, 6.19.12-200.fc43.x86_64)
vainfo: Supported profile and entrypoints
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileAV1Profile0            : VAEntrypointVLD
      VAProfileAV1Profile0            : VAEntrypointEncSlice
      VAProfileNone                   : VAEntrypointVideoProc

```

**Comment by Yot360** [comment]
> As for today, official Discord Canary (or at least the electron version they are using) enabled hardware encoding via vaapi at least for my amd RX 7800 XT and vaapi setup natively

Does this help the bitrate?

**Comment by sysrq-reisub** [comment]
> > As for today, official Discord Canary (or at least the electron version they are using) enabled hardware encoding via vaapi at least for my amd RX 7800 XT and vaapi setup natively
> 
> Does this help the bitrate?

I have not tested thoroughfully, but other people watching my streams say its perfect, try it for yourself 

Note that I tried it with the official Canary Discord version, not from Vesktop, as the issue its still present here.

**Comment by corigne** [comment]
When I was first troubleshooting, this issue was difficult to reproduce as the os/version of the client consuming the stream appeared to matter just as much as the client streaming.

Other user's troubleshooting identified it is caused by something in how discord web client handles video streams. I was under the impression that it only affects the web client, which is why it appears in vesktop but not the official desktop client with/without vencord.

Edit: I'll make sure to check vencord again today when I get into the office. I've had good luck reproducing the issue with my friends.

**Comment by corigne** [comment]
Yep, still broken.

**Comment by Yot360** [comment]
Vesktop is still broken, but discord canary looks like it has been working for me.

**Comment by corigne** [comment]
Are you using the discord desktop client or the discord web client? Afaik Vesktop is a wrapper for the web client, so the desktop version, a native electron app, is not comparable to Vesktop.
