### ISSUE TITLE
[Bug] Crash when attempting to screen share with pulseaudio

### ISSUE THREAD

**Issue by gllxflr** [Vencord/Vesktop#616]
### Discord Account

rwrv

### Operating System

Linux Mint 20.3 Cinnamon

### Linux Only ~ Desktop Environment

Cinnamon

### What happens when the bug or crash occurs?

Attempting to start a screenshare causes Vesktop to freeze when it tries to grab audio devices in the share menu.

### What is the expected behaviour?

The audio device selector works, although without app-specific audio since pulse can't do that

### How do you recreate this bug or crash?

Join a VC, click the button to start a screen share, choose an individual window, it should hang as soon as the next screen appears.

### Debug Logs

Apologies, can't give these because I've just switched to Pipewire, which works.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Curve** [comment]
Please refer to https://github.com/Vencord/venmic/issues/20. I could not reproduce the issue on Mint Edge, as well as latest Mint.

Would appreciate more input if possible, including logs and so on _(See the other issue for more information)_

**Comment by VictorMolokanov** [comment]
same problem

**Comment by Curve** [comment]
Fixed in venmic `v3.5.0`

**Comment by Curve** [comment]
> Cannot give logs, but can say the following
> 
>     * Vesktop is the latest stable Flatpak version
> 
>     * Mint was close to a fresh install
> 
>     * Pipewire is already installed and running by default, same was the case with the Xfce install on my laptop. Unsure why, given no session manager is installed with it, could possibly be related to choosing additional codecs in Mint installer? Unsure, but could be a cause of the issue. This isn't my doing as I've observed this on totally fresh installs of Mint, both Cinnamon and Xfce. This is most likely the cause of the issue.

Fun fact: I could only reproduce this on a truly fresh install of mint. As soon as I ran apt update & upgrade the problem went away

**Comment by VictorMolokanov** [comment]
i maked update, and problem is still going. i'm on mint cinamon and after updating vesktop nothing changes.

**Comment by Vendicated** [comment]
vesktop hasnt updated with the patch yet. we will do so next update or you can build from source by following instructions in readme
