### ISSUE TITLE
[Feature Request] Port vibrancy feature from vencord

### ISSUE THREAD

**Issue by Earthquake125** [Vencord/Vesktop#651]
### Motivation

Transparency on Vesktop on macOS simply makes the window transparent.

<img width="1301" alt="image" src="https://github.com/Vencord/Vesktop/assets/59297679/a0cc03be-c1a5-4219-b892-1bf0355192a2">

### Solution

Instead, I believe a Vibrancy/blur effect should be added, like Vencord on Discord:

<img width="1261" alt="image" src="https://github.com/Vencord/Vesktop/assets/59297679/cd9e0cb2-2425-43db-b2a1-ff7abe778337">

### Alternatives

N/A

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by PolisanTheEasyNick** [comment]
Looks like we can achieve it by setting  `vibrancy: "under-window"` and `visualEffectState: "followWindow"` while creating window when transparency enabled in settings.
`src/main/mainWindow.ts`:
```diff
        ...(transparent && {
            transparent: true,
-           backgroundColor: "#00000000"
+          backgroundColor: "#00000000",
+          vibrancy: "under-window",
+          visualEffectState: "followWindow"
        }),
```
Need further testing. I will get access to MacOS device tomorrow to try it and PR.

**Comment by Vendicated** [comment]
vencord already has vibrancy. it just needs to be ported

**Comment by ryzendew** [comment]
would be nice to do something like for kde as well

**Comment by Vendicated** [comment]
not really possible. this feature is powered by a macOS api that only exists there. just use a compositor like picom that can do this

**Comment by Vendicated** [comment]
turns out it was already supported, just broken due to a bug where it was using an incorrect settings key

fixed via https://github.com/Vencord/Vesktop/commit/98b0ba85a31c0df5a1b0f03f21bc019e69a4c4cc

**Comment by MaxTretikov** [comment]
Still getting this on `f9c404c` installed from homebrew unfortunately. Transparency works but is not blurred, no idea how to apply a blur effect. Using a modified version of ClearVision:

```
/**
...
 */
/* IMPORT CSS */
@import url("https://clearvision.github.io/ClearVision-v7/main.css");
@import url("https://clearvision.github.io/ClearVision-v7/betterdiscord.css");
/* SETTINGS */
:root {
  /* ACCENT COLORS ... */
  /* STATUS COLORS ... */
  /* APP BACKGROUND */
  --background-shading-percent: 100%; /* app background shading amount (0 for complete smoothness) [default: 100%] */
  --background-image: transparent; /* app background image (link must be HTTPS) [default: url(https://clearvision.github.io/images/sapphire.jpg)]*/
  --background-position: center; /* app background position [default: center] */
  --background-size: cover; /* app background size (px) [default: cover] */
  --background-attachment: fixed; /* app background attachment [default: fixed] */
  /* NOTE: changing blur here with background filter does not work */
  --background-filter: blur(12px); /* app background adjustments (ex: blur, saturation, brightness) (more info: https://developer.mozilla.org/en-US/docs/Web/CSS/filter) [default: saturate(calc(var(--saturation-factor, 1) * 1))]
  --background-blur: 1px;
  /* USER POPOUT BACKGROUND ... */
  /* USER MODAL BACKGROUND ... */
  /* HOME ICON ... */
  /* FONTS ... */
  /* CHANNEL COLORS ... */
  /* ACCESSIBILITY ... */
}

/* THEME SPECIFIC SHADING */
/* LIGHT THEME ... */

/* ASH THEME ... */

/* DARK THEME */
:is(.theme-darker, .theme-light .theme-darker) {
  /* NOTE: Changing background-shading *does* work */
  --background-shading: rgba(0, 0, 0, 0.6); /* app background shading color [default: rgba(0, 0, 0, 0.6)] */
  --card-shading: rgba(0, 0, 0, 0.3); /* cards background shading color [default: rgba(0, 0, 0, 0.3)] */
  --popout-shading: rgba(0, 0, 0, 0.7); /* popouts background shading color [default: rgba(0, 0, 0, 0.7)] */
  --modal-shading: rgba(0, 0, 0, 0.5); /* modals background shading color [default: rgba(0, 0, 0, 0.6)] */
  --input-shading: rgba(255, 255, 255, 0.05); /* inputs background shading color [default: rgba(255, 255, 255, 0.05)] */
  --normal-text: #fbfbfb; /* text color [default: #fbfbfb] */
  --muted-text: #94949c; /* muted text color [default: #94949c] */
}

/* ONYX THEME ... */

/* ADD ADDITIONAL CSS BELOW HERE */

.appMount__51fd7 .layers__160d8 { /* NOTE: doesn't work */
  /* backdrop-filter: blur(1px); */
}
```
